#!/bin/bash

# AI Gesture Password - Deployment Helper Script

echo "🚀 AI Gesture Password - Deployment Options"
echo "==========================================="
echo ""
echo "Choose your deployment method:"
echo ""
echo "1. Firebase Hosting (Recommended)"
echo "   Command: firebase login && firebase deploy"
echo ""
echo "2. GitHub Pages"
echo "   See: DEPLOYMENT.md - GitHub Pages section"
echo ""
echo "3. Netlify"
echo "   See: DEPLOYMENT.md - Netlify section"
echo ""
echo "4. Vercel"
echo "   See: DEPLOYMENT.md - Vercel section"
echo ""
echo "==========================================="
echo ""
echo "For Firebase Deployment:"
echo "1. Sign in: firebase login"
echo "2. Deploy: firebase deploy"
echo ""
echo "Your project ID: gesture-password"
echo "Hosting URL will be: https://gesture-password.firebaseapp.com"
echo ""
